
input:
  evtfile: /tmp/
  logfile: /tmp/
  userestapi: True
  datapath: /home/flareadvocate/workspace/IGRJ17354-3255/AGILE_detection_AGLJ1736-3250/data/MJD_59806_59807/

output:
  outdir: /home/flareadvocate/workspace/IGRJ17354-3255/AGILE_detection_AGLJ1736-3250/results/MJD_59806_59807/
  filenameprefix: analysis_product
  sourcename: AGLJ1736-3250
  username: downloader
  verboselvl: 1

selection:  
  tmin: 59806
  tmax: 59807
  timetype: MJD
  glon: 355.447
  glat: -0.2689
  proj: ARC
  timelist: None
  irf: H0025
  filtercode: 5
  fovradmin: 0
  fovradmax: 60
  albedorad: 80
  dq: 0
  phasecode: null
  lonpole: 180
  lpointing: null
  bpointing: null
  maplistgen: "None"

maps:
  mapsize: 40
  useEDPmatrixforEXP: false
  expstep: null
  spectralindex: 2.1
  timestep: 160
  projtype: WCS
  proj: ARC
  binsize: 0.25
  energybins:
    - 100, 10000
  fovbinnumber: 1
  offaxisangle: 30

model:
  modelfile: null
  galmode: 1
  isomode: 1
  galcoeff: null
  isocoeff: null
  galmode2: 0
  galmode2fit: 0
  isomode2: 0
  isomode2fit: 0

mle:
  ranal: 10
  ulcl: 2
  loccl: 95
  expratioevaluation: true
  expratio_minthr: 0
  expratio_maxthr: 15
  expratio_size: 10
  minimizertype: Minuit
  minimizeralg: Migrad
  minimizerdefstrategy: 2
  mindefaulttolerance: 0.01
  integratortype: 1
  contourpoints: 40
  edpcorrection: 1
  fluxcorrection: 0

ap:
  radius: 3
  timeslot: 3600

plotting:
  twocolumns: False

        